# 数据模型

![datacollection](data_objects.svg)

所有数据对象particles，simuulationcells继承于DataObject类

## 粒子容器

![particles](particles_object.svg)

In [1]:
>>> data = pipeline.compute()
>>> list(data.particles.keys())
['Particle Identifier', 'Particle Type', 'Position', 'Color']

NameError: name 'pipeline' is not defined

In [2]:
color_property = data.particles['Color']

NameError: name 'data' is not defined

In [3]:
color_property = data.particles.colors

NameError: name 'data' is not defined

## 属性对象

In [4]:
coordinates = data.particles.positions

NameError: name 'data' is not defined

In [5]:
print(coordinates[...])
[[ 73.24230194  -5.77583981  -0.87618297]
 [-49.00170135 -35.47610092 -27.92519951]
 [-50.36349869 -39.02569962 -25.61310005]
 ...,
 [ 42.71210098  59.44919968  38.6432991 ]
 [ 42.9917984   63.53770065  36.33330154]
 [ 44.17670059  61.49860001  37.5401001 ]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3464110283.py, line 2)

In [6]:
data.particles.count  # Number of particles

NameError: name 'data' is not defined

In [7]:
data.particles['Mass'].shape   # 1-dim. array

NameError: name 'data' is not defined

In [8]:
data.particles['Color'].shape  # 2-dim. array

NameError: name 'data' is not defined

In [9]:
data.particles['Color'].dtype  # Data type of property array

NameError: name 'data' is not defined

## 全局属性

DataCollection.attributes

## 数据表

Tabulated data is represented in OVITO by **DataTable** objects, which are a specialized type of **PropertyContainer**