# 数据结构

![结构图](Pipeline_overview.svg)

输入数据文件是FileSource类，经过管道进行修饰

# 从磁盘读取数据

In [1]:
from ovito.io import import_file
pipeline = import_file("simulation.dump")

RuntimeError: File does not exist:
simulation.dump

In [ ]:
print(pipeline.source)

pipeline.source  得到 FileSource对象， pipeline中的FileSource可以随时更改数据

# 应用修改器

In [1]:
from ovito.modifiers import *
pipeline.modifiers.append(ColorCodingModifier(property = 'Potential Energy'))
pipeline.modifiers.append(SliceModifier(normal = (0,0,1)))

NameError: name 'pipeline' is not defined

两种添加修改器的方法

In [2]:
pipeline.modifiers.append(CommonNeighborAnalysisModifier(cutoff=3.2, only_selected=True))

NameError: name 'pipeline' is not defined

In [3]:
modifier = CommonNeighborAnalysisModifier()
modifier.cutoff = 3.2
modifier.only_selected = True
pipeline.modifiers.append(modifier)

NameError: name 'pipeline' is not defined

# 导出数据

In [4]:
from ovito.io import export_file
export_file(pipeline, "outputdata.dump", "lammps/dump",
    columns = ["Position.X", "Position.Y", "Position.Z", "Structure Type"])

NameError: name 'pipeline' is not defined

# 得到计算结果

In [5]:
data = pipeline.compute()

NameError: name 'pipeline' is not defined

In [7]:
>>> data.objects
[SimulationCell(), Particles(), AttributeDataObject(), AttributeDataObject()]

NameError: name 'data' is not defined

得到的data是一个datacollection对象

In [8]:
>>> print(data.cell[...])
[[ 148.147995      0.            0.          -74.0739975 ]
 [   0.          148.07200623    0.          -74.03600311]
 [   0.            0.          148.0756073   -74.03780365]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2356487746.py, line 2)

In [10]:
>>> print(data.particles.positions[...])
[[ 73.24230194  -5.77583981  -0.87618297]
 [-49.00170135 -35.47610092 -27.92519951]
 [-50.36349869 -39.02569962 -25.61310005]
 ...,
 [ 42.71210098  59.44919968  38.6432991 ]
 [ 42.9917984   63.53770065  36.33330154]
 [ 44.17670059  61.49860001  37.5401001 ]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2763577061.py, line 2)

# 得到输入数据datacollection

This object also provides a compute() method returning a DataCollection

In [11]:
input_data  = pipeline.source.compute()  # pipeline.source得到的是filesource对象
output_data = pipeline.compute()

NameError: name 'pipeline' is not defined

# 可视化

In [12]:
pipeline = import_file("simulation.dump")  
pipeline.add_to_scene()    # 添加到视窗中

NameError: name 'import_file' is not defined

设置相机参数

In [14]:
from ovito.vis import Viewport
import math
vp = Viewport()
vp.type = Viewport.Type.Perspective
vp.camera_pos = (-100, -150, 150)
vp.camera_dir = (2, 3, -3)
vp.fov = math.radians(60.0)

In [15]:
vp.render_image(filename="myimage.png", size=(800,600))

<PySide2.QtGui.QImage(QSize(800, 600),format=QImage::Format_ARGB32,depth=32,devicePixelRatio=1,bytesPerLine=3200,sizeInBytes=1920000) at 0x7f4110fca8c0>